ALTER TABLE `StudySession` ADD COLUMN `user_id` INT NULL;
ALTER TABLE `Flashcard` ADD COLUMN `user_id` INT NULL;

CREATE TABLE IF NOT EXISTS `User` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password_hash` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
