<?php
// Generated by setup_mariadb_project.sh — edit as needed.
define('DB_HOST', '127.0.0.1');
define('DB_NAME', 'app_37530');
define('DB_USER', 'app_37530');
define('DB_PASS', 'c0c36e66-7749-41f3-8050-aeb5d03fca7c');

function db() {
  static $pdo;
  if (!$pdo) {
    $pdo = new PDO('mysql:host='.DB_HOST.';dbname='.DB_NAME.';charset=utf8mb4', DB_USER, DB_PASS, [
      PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
      PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);
  }
  return $pdo;
}

function apply_migrations() {
    $pdo = db();
    $migrations_dir = __DIR__ . '/migrations/';
    $migration_files = glob($migrations_dir . '*.sql');
    sort($migration_files);

    foreach ($migration_files as $migration_file) {
        // A very simple way to track executed migrations could be a file or a table.
        // For this example, we'll just run them if the file exists, which is not robust for production.
        // A more robust solution would check a `migrations` table to see if it has been run already.
        $sql = file_get_contents($migration_file);
        $pdo->exec($sql);
    }
}

apply_migrations();
